apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # EXACTLY 1 container in this pod
      containers:
        - name: frontend
          # This placeholder will be dynamically replaced by CI/CD GitHub Actions
          image: 118903272617.dkr.ecr.ap-south-1.amazonaws.com/bookflow-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  # Using LoadBalancer to expose the frontend to the broader internet via AWS ELB
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
